version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: atlas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: atlas_backend
    container_name: atlas_back
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/atlas_db
      - SPRING_DATASOURCE_USERNAME=${DB_U}
      - SPRING_DATASOURCE_PASSWORD=${DB_P}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    image: atlas_frontend
    container_name: atlas_front
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres-data: